# Jekyll Defaults
title: SpaceOddish Blog
description: Welcome to my fannish personal blog.
baseurl: "" # the subpath of your site, e.g. /blog

url: "https://spaceoddish.github.io"
github: http://github.com/spaceoddish
highlighter: rouge
markdown: kramdown
permalink: /post/:title/
paginate: 4
gems: [jekyll-paginate]
paginate_path: "/page:num"
rss_path: /feed.xml
navigation:
- text: About
  url: /about/
- text: Archives
  url: /archives/
- text: Tags
  url: /tags/
